FROM node:alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./

# COPY prisma ./prisma
# COPY libs/database/prisma/schema.prisma ./prisma/schema.prisma

RUN npm install


EXPOSE 3000

CMD [ "npm", "run", "start:dev:user" ]